### PR TITLE
Remove black dot from app icon and optimize all with optipng

### PR DESCRIPTION
**Pull request by xf-**

### CODE REVIEW

**Comment by rralf** [comment]
Hi,

the topmost commit only saves some bytes per-png. I'm not going to mess up the history for the sake of 4 byte per image, while the size is then doubled in the git repository.

Concerning the artefact, is the round icon not affected?

Thanks
  Ralf

**Comment by xf-** [comment]
image

**Comment by rralf** [comment]
Yeah -- noticed it, but where does it come from? Those icons are generated from a foreground and background vector asset. Is this spot already in one of the underlying resources? (ic_launcher_background.xml and ic_launcher_foreground.xml)

**Comment by xf-** [comment]
ic_launcher-web.png has als the artifact and i found no svg

**Comment by rralf** [comment]
No SVGs, Android Vector assets: ic_launcher_background.xml and ic_launcher_foreground.xml

the PNGs are automatically generated from these files. If PNGs contain artefacts, that these artefacts might come from their resources. Did you manually edit PNGs? If so, a complete recreation of the resources will undo your change again. Artefacts should be removed in the underlying resources first, and then we can recreate the PNGs.

**Pull request closed without merging**
